import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function GET(req: NextRequest) {
  // Check auth for cron
  const authHeader = req.headers.get("authorization");
  if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Find unreleased plans that should be released
  const plansToRelease = await prisma.planVersion.findMany({
    where: {
      isReleased: false,
      releaseAt: { lte: new Date() },
    },
    include: {
      plan: {
        include: {
          user: true,
        },
      },
    },
  });

  const results = [];

  for (const version of plansToRelease) {
    try {
      // 1. Mark as released
      await prisma.planVersion.update({
        where: { id: version.id },
        data: { isReleased: true },
      });

      // 2. Send email
      const user = version.plan.user;
      await resend.emails.send({
        from: "SwasthaLabs <coach@swasthalabs.com>",
        to: user.email,
        subject: "Your Personalized AI Diet & Workout Plan is Ready!",
        html: `
          <h1>Namaste ${user.email},</h1>
          <p>Your custom SwasthaLabs plan has been generated by our AI Coach and is now available.</p>
          <p>You can view it in your dashboard:</p>
          <a href="${process.env.NEXT_PUBLIC_SITE_URL}/dashboard">Go to Dashboard</a>
          <br/>
          <p>Stay healthy,<br/>Team SwasthaLabs</p>
        `,
      });

      results.push({ id: version.id, status: "released" });
    } catch (error: any) {
      console.error(`Error releasing plan ${version.id}:`, error);
      results.push({ id: version.id, status: "failed", error: error.message });
    }
  }

  return NextResponse.json({ released: results.length, results });
}

